#!/usr/bin/env python3
"""
withdraw_requests.py — export'taki bekleyen takip isteklerini geri çeker.

Listeyi downloads/ altındaki pending_follow_requests.(html|json) dosyasından
okur, her profili açar ve başlıktaki buton hâlâ "Requested" ise isteği iptal eder.

Kullanım:
    ./geri_cek.sh --dry-run            # tıklamadan sadece durumları göster
    ./geri_cek.sh                      # tek sekme, işlemler arası 4–6 sn
    ./geri_cek.sh --watch              # tek sekme, her adımı ekranda işaretler
    ./geri_cek.sh --hedef-dk 60        # listeyi ~60 dakikaya yay (paralel sekmelerle)
    ./geri_cek.sh --parallel 4         # 4 sekme aynı anda

Güvenlik:
    - Butonu "Following" olan (isteği kabul etmiş) hesaplara dokunmaz.
    - Instagram engellerse ("Try Again Later", "birkaç dakika bekle", doğrulama
      sayfası, sessizce geri alınan tıklamalar) bütün sekmeler durur, terminale
      ne zaman/kaçıncı işlemde olduğu yazılır ve logs/rate_limit.log'a eklenir.
      İlerleme kaydedilir; aynı komut kaldığı yerden devam eder.
"""

from __future__ import annotations

import argparse
import asyncio
import html
import json
import math
import random
import re
import signal
import sys
import time
from collections.abc import Awaitable, Callable
from dataclasses import dataclass, field
from datetime import datetime
from getpass import getpass
from pathlib import Path

from playwright.async_api import (
    Error as PWError,
    Page,
    TimeoutError as PWTimeout,
    async_playwright,
)

from ig_export import DOWNLOADS_DIR, LOG_DIR, LOGIN_URL, PROFILES_DIR, ROOT, log

STATE_FILE = ROOT / "withdraw_state.json"
RATE_LOG = LOG_DIR / "rate_limit.log"

REQUESTED_RE = re.compile(r"^\s*(requested|i̇stek gönderildi|istek gönderildi)\s*$", re.I)
FOLLOWING_RE = re.compile(r"^\s*(following|takiptesin|takip ediliyor)\s*$", re.I)
FOLLOW_RE = re.compile(r"^\s*(follow|follow back|takip et|sen de takip et|geri takip et)\s*$", re.I)
# Onay penceresindeki "iptal et" butonu. Düz "Cancel" pencereyi kapatır, o değil.
CONFIRM_RE = re.compile(
    r"^\s*(unfollow|cancel request|withdraw( request)?|takibi bırak|isteği (iptal et|geri çek))\s*$",
    re.I,
)
BLOCKED_RE = re.compile(
    r"(try again later|we restrict certain activity|action blocked|please wait a few minutes"
    r"|daha sonra tekrar dene|birkaç dakika bekle)",
    re.I,
)
NOT_FOUND_RE = re.compile(
    r"(this page isn.t available|profile isn.t available|bu sayfaya ulaşılamıyor)", re.I
)
CHALLENGE_URL_RE = re.compile(r"/(challenge|checkpoint|accounts/suspended)", re.I)
LOGIN_URL_RE = re.compile(r"/accounts/login|login\.php", re.I)
HEADER_BUTTONS = "header button, header div[role='button']"

# Tekrar çalıştırmada yeniden denenmeyecek sonuçlar
FINAL_SKIPS = {"following", "no_request", "not_found"}
# Bunlardan biri gelirse bütün sekmeler durur
STOP_RESULTS = {"blocked", "checkpoint", "logged_out"}
# Tek sekmede bir profilin yaklaşık süresi (sayfa + tıklama + doğrulama), tahmin için
PER_ITEM_SEC = 7.0
PER_ITEM_SEC_WATCH = 16.0


# --------------------------------------------------------------------------
# Listeyi export'tan okuma
# --------------------------------------------------------------------------

PENDING_NAMES = ("pending_follow_requests.json", "pending_follow_requests.html")
USERNAME_RE = re.compile(r"^[A-Za-z0-9._]{1,30}$")
# Export'un dili hesabın diline göre değişiyor: "Username" / "Kullanıcı adı"
USER_LABEL_RE = re.compile(r"user\s*name|kullan[ıi]c[ıi]\s*ad[ıi]", re.I)
# Başlıktaki sahip: "Generated by x on …" / "… tarihinde x oluşturdu"
OWNER_RES = [
    re.compile(r"generated by\s+@?([A-Za-z0-9._]{1,30})", re.I),
    re.compile(r"@?([A-Za-z0-9._]{1,30})\s+oluşturdu", re.I),
]


def _text(fragment: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", fragment))).strip()


def _clean_username(value: str) -> str:
    value = value.strip().lstrip("@")
    return value if USERNAME_RE.match(value) else ""


def _instagram_username(href: str) -> str:
    """Sadece instagram.com linklerinden okur; bio'daki Spotify/VSCO linkleri değil."""
    m = re.match(r"https?://(?:www\.)?instagram\.com/(?:_u/)?([^/?#]+)", href.strip(), re.I)
    return _clean_username(m.group(1)) if m else ""


def export_owner(path: Path) -> str | None:
    """HTML export'u oluşturan hesap, dosya başlığından."""
    if path.suffix != ".html":
        return None
    try:
        with path.open(encoding="utf-8", errors="ignore") as fh:
            raw = fh.read(200_000)  # başlıktan önce ~14 KB'lık <style> bloğu var
    except OSError:
        return None
    end = raw.find("</header>")
    head = _text(re.sub(r"<style\b.*?</style>", " ", raw[: end if end >= 0 else None], flags=re.S | re.I))
    for pattern in OWNER_RES:
        m = pattern.search(head)
        if m:
            return m.group(1)
    return None


def owner_of(path: Path) -> str | None:
    """Önce dosya başlığı, yoksa instagram-<hesap>-<tarih>-… klasör adı."""
    owner = export_owner(path)
    if owner:
        return owner
    for part in path.parts:
        m = re.match(r"instagram-(.+)-\d{4}-\d{2}-\d{2}-", part)
        if m:
            return m.group(1)
    return None


def find_pending_files() -> list[Path]:
    """downloads/ altındaki tüm listeler, en yeni önce (klasör yapısı fark etmez)."""
    if not DOWNLOADS_DIR.exists():
        return []
    files = [p for p in DOWNLOADS_DIR.rglob("pending_follow_requests.*") if p.name in PENDING_NAMES]
    return sorted(files, key=lambda p: p.stat().st_mtime, reverse=True)


def find_pending_file(account: str) -> Path | None:
    """Bu hesaba ait en yeni liste. Sahibi okunamayan dosya (ör. JSON) sadece
    downloads/<hesap>/ altındaysa sayılır — başka hesabın listesini bu hesabın
    oturumuyla işlememek için. Diğer durumlarda --file ile açıkça verilmeli."""
    folder = re.sub(r"\W", "_", account)
    for path in find_pending_files():
        owner = owner_of(path)
        if owner is not None:
            if owner.lower() == account.lower():
                return path
        elif folder in path.relative_to(DOWNLOADS_DIR).parts:
            return path
    return None


def parse_html(path: Path) -> list[tuple[str, str]]:
    raw = path.read_text(encoding="utf-8")
    body = raw[raw.find("</header>"):] if "</header>" in raw else raw

    # Her istek bir tablo, satırlar [etiket, değer]; tarih tablodan sonraki ilk div.
    # Etiket metnine değil yapıya bakıyoruz ki Türkçe/İngilizce fark etmesin.
    result = []
    for chunk in re.split(r"(?=<table\b)", body):
        table = re.match(r"<table\b.*?</table>", chunk, re.S | re.I)
        if not table:
            continue
        rows = []
        for tr in re.findall(r"<tr\b.*?</tr>", table.group(0), re.S | re.I):
            cells = re.findall(r"<td\b[^>]*>(.*?)</td>", tr, re.S | re.I)
            if cells:
                label = _text(cells[0]) if len(cells) > 1 else ""
                rows.append((label, _text(cells[-1]), re.findall(r'href="([^"]+)"', cells[-1])))

        username = ""
        for label, value, hrefs in rows:
            if USER_LABEL_RE.search(label):
                username = _clean_username(value) or next(filter(None, map(_instagram_username, hrefs)), "")
                break
        if not username:
            # Etiket tanınmadı: instagram linki, yoksa link olmayan son geçerli değer
            for _, value, hrefs in reversed(rows):
                username = next(filter(None, map(_instagram_username, [*hrefs, value])), "")
                if not username and not value.lower().startswith("http"):
                    username = _clean_username(value)
                if username:
                    break
        if not username:
            continue

        date = re.search(r"<div\b[^>]*>([^<]{1,60})</div>", chunk[table.end():])
        result.append((username, html.unescape(date.group(1)).strip() if date else ""))

    if not result:
        # Eski biçim: sadece profil linkleri
        for href in re.findall(r'href="([^"]+)"', body):
            username = _instagram_username(href)
            if username:
                result.append((username, ""))
    return result


def parse_json(path: Path) -> list[tuple[str, str]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    items = data.get("relationships_follow_requests_sent", data) if isinstance(data, dict) else data
    result = []
    for item in items:
        sld = (item.get("string_list_data") or [{}])[0]
        username = (
            _clean_username(str(sld.get("value") or ""))
            or _clean_username(str(item.get("title") or ""))
            or _instagram_username(str(sld.get("href") or ""))
        )
        ts = sld.get("timestamp")
        date = datetime.fromtimestamp(ts).strftime("%b %d, %Y %H:%M") if ts else ""
        if username:
            result.append((username, date))
    return result


def load_pending(path: Path) -> list[tuple[str, str]]:
    items = parse_json(path) if path.suffix == ".json" else parse_html(path)
    seen: set[str] = set()
    unique = []
    for username, date in items:
        if username.lower() not in seen:
            seen.add(username.lower())
            unique.append((username, date))
    return unique


# --------------------------------------------------------------------------
# --watch: her adımı ekranda işaretle ve yavaşlat
# --------------------------------------------------------------------------

WATCH = False
GRAY, RED, GREEN, AMBER = "#475569", "#e11d48", "#16a34a", "#d97706"


async def show_step(page: Page, text: str, color: str = GRAY, hold_ms: int = 0) -> None:
    """Sayfanın altına adım açıklaması basar (sadece --watch)."""
    if not WATCH:
        return
    try:
        await page.evaluate(
            """([text, color]) => {
                let el = document.getElementById('__geri_cek');
                if (!el) {
                    el = document.createElement('div');
                    el.id = '__geri_cek';
                    document.body.appendChild(el);
                }
                Object.assign(el.style, {
                    position: 'fixed', bottom: '24px', left: '50%',
                    transform: 'translateX(-50%)', zIndex: 2147483647,
                    background: color, color: '#fff', padding: '12px 22px',
                    borderRadius: '12px', font: '600 17px system-ui, sans-serif',
                    boxShadow: '0 8px 28px rgba(0,0,0,.35)', pointerEvents: 'none',
                    maxWidth: '90vw', textAlign: 'center',
                });
                el.textContent = text;
            }""",
            [text, color],
        )
    except PWError:
        pass
    if hold_ms:
        await page.wait_for_timeout(hold_ms)


async def highlight(page: Page, locator, text: str, color: str, hold_ms: int) -> None:
    """Butonun etrafına çerçeve çizer, açıklama basar, izlemen için bekler."""
    if not WATCH:
        return
    try:
        await locator.evaluate(
            "(el, c) => { el.scrollIntoView({block: 'center'});"
            " el.style.outline = `4px solid ${c}`; el.style.outlineOffset = '4px';"
            " el.style.borderRadius = '8px'; }",
            color,
        )
    except PWError:
        pass
    await show_step(page, text, color, hold_ms)


# --------------------------------------------------------------------------
# Profil sayfası
# --------------------------------------------------------------------------


async def header_state(page: Page) -> tuple[str, list[str]]:
    """Profil başlığındaki takip butonunun durumu: requested/following/follow/unknown."""
    try:
        texts = [t.strip() for t in await page.locator(HEADER_BUTTONS).all_inner_texts()]
    except PWError:
        return "unknown", []
    texts = [t for t in texts if t][:15]
    for pattern, name in ((REQUESTED_RE, "requested"), (FOLLOWING_RE, "following"), (FOLLOW_RE, "follow")):
        if any(pattern.match(t) for t in texts):
            return name, texts
    return "unknown", texts


async def body_text(page: Page) -> str:
    try:
        return await page.locator("body").inner_text(timeout=2_000)
    except PWError:
        return ""


def url_problem(page: Page) -> str | None:
    if CHALLENGE_URL_RE.search(page.url):
        return "checkpoint"
    if LOGIN_URL_RE.search(page.url):
        return "logged_out"
    return None


async def wait_profile(page: Page, timeout: float = 20.0) -> str:
    """Profil yüklenene kadar bekler (sabit bekleme yerine). "Requested" görülünce
    hemen döner; "Follow"/"Following" ise sayfa yüklenirken geçici görünebildiği
    için 1 sn aynı kalmasını bekler."""
    loop = asyncio.get_running_loop()
    end = loop.time() + timeout
    last, since = None, 0.0
    while loop.time() < end:
        problem = url_problem(page)
        if problem:
            return problem
        state, _ = await header_state(page)
        if state == "requested":
            return state
        if state in ("follow", "following"):
            if state != last:
                last, since = state, loop.time()
            elif loop.time() - since >= 1.0:
                return state
        else:
            last = None
            text = await body_text(page)
            if NOT_FOUND_RE.search(text):
                return "not_found"
            if BLOCKED_RE.search(text):
                return "blocked"
        await asyncio.sleep(0.25)
    return last or "unknown"


async def withdraw_one(page: Page, username: str, dry_run: bool = False, stopping=lambda: False) -> str:
    """
    Dönüş: withdrawn / following / no_request / not_found / failed /
           blocked / checkpoint / logged_out   (dry-run'da: requested)
           aborted — başka sekme engel gördüğü için tıklamadan bırakıldı
    """
    await page.goto(f"https://www.instagram.com/{username}/", wait_until="domcontentloaded", timeout=45_000)
    state = await wait_profile(page)

    if state in STOP_RESULTS:
        return state
    if state == "not_found":
        await show_step(page, f"@{username} — hesap yok, atlanıyor", AMBER, 2_000)
        return "not_found"
    await show_step(page, f"@{username} açıldı — takip butonu kontrol ediliyor…", GRAY, 1_200)
    if state == "following":
        await show_step(page, f"@{username} isteği kabul etmiş (Following) — DOKUNULMUYOR", AMBER, 2_500)
        return "following"
    if state == "follow":
        await show_step(page, f"@{username} için bekleyen istek yok — atlanıyor", AMBER, 2_000)
        return "no_request"
    if state != "requested":
        _, texts = await header_state(page)
        log(f"  {username}: buton tanınmadı {texts}")
        return "failed"
    if dry_run:
        return "requested"
    if stopping():
        return "aborted"

    button = page.locator("header").get_by_role("button", name=REQUESTED_RE).first
    await highlight(page, button, f"@{username} — 'Requested' bulundu → tıklanıyor", RED, 2_000)
    try:
        await button.click(timeout=10_000)
    except PWError:
        await page.locator("header div[role='button']").filter(has_text=REQUESTED_RE).first.click(timeout=10_000)

    # Onay penceresi gelince "Unfollow"a bas (gelmezse bazı sürümler doğrudan iptal ediyor)
    confirm = page.get_by_role("dialog").get_by_role("button", name=CONFIRM_RE).first
    try:
        await confirm.wait_for(state="visible", timeout=5_000)
        await highlight(page, confirm, "Onay penceresi → 'Unfollow' tıklanıyor", RED, 1_800)
        await confirm.click(timeout=10_000)
    except PWTimeout:
        pass

    # Doğrula: buton "Follow"a dönmeli
    for _ in range(40):  # ~10 sn
        await asyncio.sleep(0.25)
        problem = url_problem(page)
        if problem:
            return problem
        if BLOCKED_RE.search(await body_text(page)):
            return "blocked"
        state, _ = await header_state(page)
        if state == "follow":
            follow_btn = page.locator("header").get_by_role("button", name=FOLLOW_RE).first
            await highlight(page, follow_btn, f"✓ @{username} — istek geri çekildi (buton artık 'Follow')", GREEN, 2_500)
            return "withdrawn"
    return "failed"


async def is_logged_out(page: Page) -> bool:
    if LOGIN_URL_RE.search(page.url):
        return True
    try:
        return await page.locator("input[name='username'], input[name='email']").count() > 0
    except PWError:
        return False


async def ensure_logged_in(page: Page, account: str, headless: bool) -> bool:
    await page.goto("https://www.instagram.com/", wait_until="domcontentloaded", timeout=60_000)
    await page.wait_for_timeout(3_000)
    if CHALLENGE_URL_RE.search(page.url):
        log("Instagram doğrulama istiyor — --headless olmadan çalıştırıp tarayıcıda tamamla.")
        return False
    if not await is_logged_out(page):
        return True
    if headless:
        log("oturum kapalı — bir kez --headless olmadan çalıştırıp giriş yap.")
        return False

    password = getpass(f"{account} şifresi: ") if sys.stdin.isatty() else None
    await page.goto(LOGIN_URL, wait_until="domcontentloaded", timeout=60_000)
    if password:
        try:
            await page.fill("input[name='username']", account, timeout=20_000)
            await page.fill("input[name='password']", password, timeout=20_000)
            await page.press("input[name='password']", "Enter")
        except PWError as exc:
            log(f"login formu doldurulamadı: {exc}")
    log("2FA veya doğrulama varsa tarayıcıda tamamla — 3 dk bekleniyor…")
    for _ in range(60):
        await page.wait_for_timeout(3_000)
        if not await is_logged_out(page) and not CHALLENGE_URL_RE.search(page.url):
            log("giriş başarılı.")
            return True
    return False


# --------------------------------------------------------------------------
# Çalıştırma: sekmeler, hız, engel raporu
# --------------------------------------------------------------------------

LABELS = {
    "withdrawn": "✓ geri çekildi",
    "requested": "hâlâ bekliyor (dry-run)",
    "following": "atlandı — isteği kabul etmiş, dokunulmadı",
    "no_request": "atlandı — bekleyen istek yok artık",
    "not_found": "atlandı — hesap yok/kapalı",
    "failed": "✗ başarısız",
    "blocked": "✗ Instagram engelledi",
    "checkpoint": "✗ Instagram doğrulama istiyor",
    "logged_out": "✗ oturum düştü",
}

STOP_TITLES = {
    "blocked": "INSTAGRAM ENGELLEDİ (rate limit)",
    "checkpoint": "INSTAGRAM DOĞRULAMA İSTİYOR (checkpoint)",
    "logged_out": "OTURUM DÜŞTÜ — Instagram çıkış yaptırdı",
    "silent": "ÜST ÜSTE BAŞARISIZ — büyük ihtimalle sessiz engel",
    "user": "KULLANICI DURDURDU",
}

SUMMARY = {
    "requested": "hâlâ bekliyor (geri çekilebilir)",
    "withdrawn": "geri çekildi",
    "following": "kabul etmiş, dokunulmadı",
    "no_request": "bekleyen istek yok",
    "not_found": "hesap yok/kapalı",
    "failed": "başarısız",
    "blocked": "Instagram engelledi",
    "checkpoint": "doğrulama istendi",
    "logged_out": "oturum düştü",
}


@dataclass(frozen=True)
class Islem:
    """Geri çekme ve istek atma aynı çalıştırıcıyı kullanır (sekmeler, --hedef-dk,
    engel raporu, kaldığı yerden devam); aradaki farklar burada."""

    name: str  # rate_limit.log'daki "islem"
    fn: Callable[..., Awaitable[str]]  # (page, username, dry_run=, stopping=) -> sonuç
    done: str  # başarı sonucu; state'te bu anahtarın altında tutulur
    verb: str  # "geri çekildi"
    noun: str  # "geri çekilen"
    final_skips: frozenset[str]  # tekrar çalıştırmada yeniden denenmeyecek sonuçlar
    labels: dict[str, str]  # profil başına log satırı
    summary: dict[str, str]  # özet tablosu
    state_file: Path | None  # None: STATE_FILE
    log_key: str  # rate_limit.log'daki sayaç alanı

    @property
    def state_path(self) -> Path:
        # STATE_FILE çağrı anında okunur; testler onu geçici klasöre çeviriyor
        return self.state_file or STATE_FILE


GERI_CEK = Islem(
    name="geri_cek",
    fn=withdraw_one,
    done="withdrawn",
    verb="geri çekildi",
    noun="geri çekilen",
    final_skips=frozenset(FINAL_SKIPS),
    labels=LABELS,
    summary=SUMMARY,
    state_file=None,
    log_key="geri_cekilen",
)


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT)) if path.is_relative_to(ROOT) else str(path)


def fmt_duration(seconds: float) -> str:
    seconds = int(seconds)
    h, rest = divmod(seconds, 3600)
    m, s = divmod(rest, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"


@dataclass
class Run:
    args: argparse.Namespace
    account: str
    total: int
    state: dict
    acc_state: dict
    islem: Islem
    parallel: int
    interval: float | None  # --hedef-dk: profiller arası ortak aralık (sn)
    counts: dict = field(default_factory=dict)
    processed: int = 0
    succeeded: int = 0
    consecutive_fail: int = 0
    stop_reason: str | None = None
    announced: bool = False
    started: float = field(default_factory=time.monotonic)
    next_slot: float = 0.0
    last_stats: float = field(default_factory=time.monotonic)

    @property
    def stopping(self) -> bool:
        return self.stop_reason is not None

    def rate_per_min(self) -> float:
        elapsed = time.monotonic() - self.started
        return self.processed / elapsed * 60 if elapsed > 0 else 0.0

    def record(self, n: int, username: str, date: str, result: str) -> None:
        self.processed += 1
        self.counts[result] = self.counts.get(result, 0) + 1
        where = f" ({date})" if date else ""
        log(f"[{n}/{self.total}] {username}{where}: {self.islem.labels.get(result, result)}")
        if self.args.dry_run:
            return
        now = datetime.now().isoformat(timespec="seconds")
        if result == self.islem.done:
            self.succeeded += 1
            self.acc_state[self.islem.done][username] = now
            self.acc_state["skipped"].pop(username, None)
            self.consecutive_fail = 0
        elif result in self.islem.final_skips:
            self.acc_state["skipped"][username] = result
            self.consecutive_fail = 0
        else:
            self.acc_state["skipped"][username] = result
            if result == "failed":
                self.consecutive_fail += 1
        save_state(self.state, self.islem.state_path)

    def maybe_stats(self) -> None:
        now = time.monotonic()
        if self.processed % 25 and now - self.last_stats < 60:
            return
        self.last_stats = now
        elapsed = now - self.started
        left = self.total - self.processed
        eta = left / (self.processed / elapsed) if self.processed else 0
        log(
            f"— ilerleme {self.processed}/{self.total} · {self.succeeded} {self.islem.verb} · "
            f"hız {self.rate_per_min():.1f} profil/dk · geçen {fmt_duration(elapsed)} · "
            f"kalan ~{fmt_duration(eta)}"
        )

    async def stop(self, reason: str, page: Page | None = None, username: str = "") -> None:
        """Bütün sekmeleri durdurur ve terminale bir kez rapor basar."""
        if self.announced:
            return
        self.announced = True
        self.stop_reason = reason
        elapsed = time.monotonic() - self.started
        message = ""
        shot = None
        if page is not None:
            text = await body_text(page)
            m = BLOCKED_RE.search(text)
            if m:
                message = re.sub(r"\s+", " ", text[m.start() : m.end() + 120]).strip()
            try:
                LOG_DIR.mkdir(exist_ok=True)
                shot = LOG_DIR / f"engel-{datetime.now():%Y%m%d-%H%M%S}.png"
                await page.screenshot(path=str(shot))
            except PWError:
                shot = None

        bar = "=" * 64
        lines = [
            "",
            bar,
            f"  ⛔ {STOP_TITLES.get(reason, reason)}",
            bar,
            f"  saat            : {datetime.now():%H:%M:%S}",
            f"  son profil      : @{username}" if username else None,
            f"  başlangıçtan    : {fmt_duration(elapsed)} sonra",
            f"  bu çalıştırmada : {self.processed} profil işlendi, {self.succeeded} {self.islem.verb}",
            f"  hız             : {self.rate_per_min():.1f} profil/dk  ({self.parallel} sekme)",
            f"  sayfadaki mesaj : \"{message}\"" if message else None,
            f"  ekran görüntüsü : {rel(shot)}" if shot else None,
            "  İlerleme kaydedildi. Birkaç saat sonra aynı komutla kaldığı yerden devam eder."
            if reason in ("blocked", "silent")
            else "  İlerleme kaydedildi. Tarayıcıyı --headless olmadan açıp durumu kontrol et."
            if reason in ("checkpoint", "logged_out")
            else "  İlerleme kaydedildi.",
            bar,
            "",
        ]
        print("\a" + "\n".join(l for l in lines if l is not None), flush=True)

    async def take_slot(self) -> None:
        """--hedef-dk: sekmeler ortak bir sıradan zaman alır; böylece toplam hız sabit kalır."""
        if not self.interval:
            return
        loop = asyncio.get_running_loop()
        slot = max(loop.time(), self.next_slot)
        self.next_slot = slot + self.interval * random.uniform(0.8, 1.2)
        await self.sleep_until(slot)

    async def sleep_until(self, when: float) -> None:
        loop = asyncio.get_running_loop()
        while not self.stopping and (left := when - loop.time()) > 0:
            await asyncio.sleep(min(0.25, left))

    async def pause(self, page: Page, seconds: float, reason: str) -> None:
        """Tek sekmede terminalde (ve --watch'ta tarayıcıda) geri sayım; paralelde sessiz bekleme."""
        loop = asyncio.get_running_loop()
        end = loop.time() + seconds
        tty = sys.stdout.isatty() and self.parallel == 1
        while not self.stopping and (left := end - loop.time()) > 0:
            text = f"⏳ {reason} — sonraki profile {math.ceil(left)} sn"
            if tty:
                print(f"\r   {text}   ", end="", flush=True)
            await show_step(page, text, GRAY)
            await asyncio.sleep(min(1.0, left))
        if tty:
            print("\r" + " " * 70 + "\r", end="", flush=True)


async def worker(run: Run, ctx, queue: asyncio.Queue) -> None:
    page = await ctx.new_page()
    fail_limit = max(3, run.parallel + 1)
    try:
        while not run.stopping:
            try:
                n, username, date = queue.get_nowait()
            except asyncio.QueueEmpty:
                break
            await run.take_slot()
            if run.stopping:
                break
            try:
                result = await run.islem.fn(page, username, dry_run=run.args.dry_run,
                                            stopping=lambda: run.stopping)
            except PWError as exc:
                log(f"[{n}/{run.total}] {username}: hata {str(exc).splitlines()[0][:120]}")
                result = "failed"
            if result == "aborted":
                break  # kayda geçmez; sonraki çalıştırmada yeniden denenir
            run.record(n, username, date, result)
            run.maybe_stats()

            if result in STOP_RESULTS:
                await run.stop(result, page, username)
                break
            if run.consecutive_fail >= fail_limit:
                await run.stop("silent", page, username)
                break
            if not run.interval:
                if result == run.islem.done:
                    await run.pause(page, random.uniform(run.args.min_delay, run.args.max_delay),
                                    "Instagram engeli yememek için bekleniyor")
                else:
                    await run.pause(page, random.uniform(1, 2), "atlandı")
    finally:
        try:
            await page.close()
        except PWError:
            pass


async def open_context(pw, account: str, args):
    return await pw.chromium.launch_persistent_context(
        user_data_dir=str(PROFILES_DIR / re.sub(r"\W", "_", account)),
        channel="chrome",
        headless=args.headless,
        slow_mo=300 if args.watch else 0,
        # Ctrl+C'yi script yönetiyor (sekmeler eldeki profili bitirip dursun)
        handle_sigint=False,
        locale="en-US",
        viewport={"width": 1280, "height": 900},
        args=["--disable-blink-features=AutomationControlled"],
    )


async def run_all(run: Run, todo: list[tuple[str, str]]) -> None:
    loop = asyncio.get_running_loop()

    def on_sigint() -> None:
        log("durduruluyor — açık sekmeler eldeki profili bitiriyor (hemen çıkmak için tekrar Ctrl+C)…")
        run.stop_reason = run.stop_reason or "user"
        loop.remove_signal_handler(signal.SIGINT)

    try:
        loop.add_signal_handler(signal.SIGINT, on_sigint)
    except (NotImplementedError, RuntimeError):
        pass

    async with async_playwright() as pw:
        ctx = await open_context(pw, run.account, run.args)
        try:
            first = ctx.pages[0] if ctx.pages else await ctx.new_page()
            if not await ensure_logged_in(first, run.account, run.args.headless):
                run.stop_reason = "logged_out"
                log("HATA: giriş yapılamadı.")
                return

            queue: asyncio.Queue = asyncio.Queue()
            for n, (username, date) in enumerate(todo, 1):
                queue.put_nowait((n, username, date))
            run.started = time.monotonic()
            run.next_slot = loop.time()
            await asyncio.gather(*(worker(run, ctx, queue) for _ in range(run.parallel)))

            if run.stop_reason == "user" and not run.announced:
                await run.stop("user")
            if WATCH and not run.stopping:
                await show_step(first, "Bitti — tarayıcı 6 sn sonra kapanacak", GRAY, 6_000)
        finally:
            save_state(run.state, run.islem.state_path)
            try:
                await ctx.close()
            except PWError:
                pass


# --------------------------------------------------------------------------


def load_state(path: Path | None = None) -> dict:
    path = path or STATE_FILE
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {}


def save_state(state: dict, path: Path | None = None) -> None:
    (path or STATE_FILE).write_text(json.dumps(state, indent=2, ensure_ascii=False), encoding="utf-8")


def append_rate_log(run: Run) -> None:
    """Her çalıştırmanın sonucu — farklı hızlarda ne zaman engel geldiğini karşılaştırmak için."""
    elapsed = time.monotonic() - run.started
    entry = {
        "zaman": datetime.now().isoformat(timespec="seconds"),
        "hesap": run.account,
        "islem": run.islem.name,
        "sonuc": run.stop_reason or "tamamlandi",
        "sekme": run.parallel,
        "hedef_dk": run.args.hedef_dk,
        "bekleme_sn": None if run.interval else [run.args.min_delay, run.args.max_delay],
        "islenen": run.processed,
        run.islem.log_key: run.succeeded,
        "sure_sn": round(elapsed),
        "hiz_profil_dk": round(run.rate_per_min(), 1),
    }
    try:
        LOG_DIR.mkdir(exist_ok=True)
        with RATE_LOG.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry, ensure_ascii=False) + "\n")
    except OSError:
        pass


def plan_speed(args: argparse.Namespace, count: int) -> tuple[int, float | None]:
    """Sekme sayısı ve (--hedef-dk varsa) profiller arası ortak aralık; tahmini terminale yazar."""
    per_item = PER_ITEM_SEC_WATCH if args.watch else PER_ITEM_SEC
    interval = None
    if args.hedef_dk:
        interval = args.hedef_dk * 60 / count
        parallel = args.parallel or min(10, max(1, math.ceil(per_item / interval) + 1))
    else:
        parallel = args.parallel or 1
    if args.watch and parallel > 1:
        log("--watch tek sekmede izlenebiliyor; sekme sayısı 1'e indirildi.")
        parallel = 1
    parallel = max(1, min(parallel, count))

    if interval:
        reachable = parallel / per_item * 60  # profil/dk
        wanted = 60 / interval
        log(
            f"hedef ~{args.hedef_dk:g} dk: {parallel} sekme, ~{interval:.1f} sn'de bir profil "
            f"(~{wanted:.0f} profil/dk)"
        )
        if reachable < wanted * 0.9:
            minutes = count / reachable
            log(f"UYARI: {parallel} sekmeyle bu hıza yetişilemez; tahmini süre ~{fmt_duration(minutes * 60)}.")
    else:
        avg = per_item + (args.min_delay + args.max_delay) / 2
        log(f"{parallel} sekme, tahmini süre ~{fmt_duration(count * avg / parallel)}.")
    if not args.dry_run and count > 150:
        log("Uzun liste: Instagram bir noktada engel koyabilir. Olursa bütün sekmeler durur, "
            "terminale ne zaman geldiği yazılır; aynı komut kaldığı yerden devam eder.")
    log("Ctrl+C ile durdurabilirsin (ilerleme kaydedilir).")
    return parallel, interval


def execute(run: Run, todo: list[tuple[str, str]], list_size: int) -> int:
    """Çalıştırır, ilerlemeyi ve hız kaydını yazar, özeti basar; çıkış kodunu döner."""
    args, islem = run.args, run.islem
    try:
        asyncio.run(run_all(run, todo))
    except KeyboardInterrupt:
        run.stop_reason = run.stop_reason or "user"
        log("hemen durduruldu.")
    finally:
        if not args.dry_run:
            save_state(run.state, islem.state_path)
            append_rate_log(run)

    elapsed = time.monotonic() - run.started
    print("\n" + "=" * 64)
    print("ÖZET" + (" (dry-run, hiçbir şey değişmedi)" if args.dry_run else ""))
    print("=" * 64)
    for key, value in sorted(run.counts.items(), key=lambda kv: -kv[1]):
        print(f"  {islem.summary.get(key, key):<34} {value}")
    print(f"\n  süre: {fmt_duration(elapsed)} · hız: {run.rate_per_min():.1f} profil/dk · {run.parallel} sekme")
    if run.stop_reason and run.stop_reason != "user":
        print(f"  durma sebebi: {STOP_TITLES.get(run.stop_reason, run.stop_reason)}")
    if not args.dry_run:
        print(f"  Toplam {islem.noun} (tüm çalıştırmalar): {len(run.acc_state[islem.done])}/{list_size}")
        print(f"  Hız kaydı: {rel(RATE_LOG)}")
    return 1 if run.stop_reason in STOP_RESULTS | {"silent"} else 0


def pick_account(given: str | None) -> str:
    if given:
        return given.lstrip("@")
    # downloads/ altındaki listelerin sahipleri; tek hesap varsa sormadan onu seç
    owners = list(dict.fromkeys(o for p in find_pending_files() if (o := owner_of(p))))
    if len(owners) == 1:
        return owners[0]
    if not sys.stdin.isatty():
        hint = f" Bulunan listeler: {', '.join(owners)}" if owners else ""
        sys.exit(f"HATA: hangi hesap? --account ile ver.{hint}")
    if owners:
        print(f"downloads/ altında birden fazla hesabın listesi var: {', '.join(owners)}")
    return input("Kullanıcı adı: ").strip().lstrip("@")


def main() -> int:
    ap = argparse.ArgumentParser(description="Bekleyen takip isteklerini geri çek")
    ap.add_argument("--account", help="kullanıcı adı (tek hesap varsa otomatik)")
    ap.add_argument("--file", help="pending_follow_requests.html/json yolu (varsayılan: en yeni export)")
    ap.add_argument("--dry-run", action="store_true", help="tıklama, sadece durumları göster")
    ap.add_argument("--limit", type=int, help="en fazla bu kadar işlem yap")
    ap.add_argument("--min-delay", type=float, default=4, help="işlemler arası min bekleme (sn)")
    ap.add_argument("--max-delay", type=float, default=6, help="işlemler arası max bekleme (sn)")
    ap.add_argument("--hedef-dk", type=float, help="listeyi yaklaşık bu kadar dakikada bitir (sekme sayısı otomatik)")
    ap.add_argument("--parallel", type=int, help="aynı anda kaç sekme (varsayılan 1; --hedef-dk ile otomatik)")
    ap.add_argument("--newest-first", action="store_true", help="en yeni istekten başla")
    ap.add_argument("--headless", action="store_true", help="tarayıcıyı gösterme")
    ap.add_argument("--watch", action="store_true", help="izleme modu: yavaş, butonları işaretler")
    args = ap.parse_args()

    global WATCH
    if args.watch:
        WATCH = True
        args.headless = False

    account = pick_account(args.account)
    source = Path(args.file).expanduser().resolve() if args.file else find_pending_file(account)
    if not source or not source.exists():
        files = find_pending_files()
        others = sorted({o for p in files if (o := owner_of(p))} - {account})
        unknown = [p for p in files if owner_of(p) is None]
        hint = ""
        if others:
            hint += f"\ndownloads/ altındaki listeler şu hesaplara ait: {', '.join(others)}."
        if unknown:
            hint += (
                f"\nSahibi okunamayan liste var: {unknown[0].relative_to(ROOT)} — "
                f"bu hesabınsa: ./geri_cek.sh --account {account} --file {unknown[0].relative_to(ROOT)}"
            )
        if not hint:
            hint = "\nExport zip'ini aç, içindeki pending_follow_requests dosyasını downloads/ altına koy."
        sys.exit(f"HATA: @{account} için pending_follow_requests dosyası bulunamadı.{hint}")

    # Bir hesabın listesini öbür hesabın oturumuyla işlememek için
    owner = owner_of(source)
    if owner and owner.lower() != account.lower():
        sys.exit(
            f"HATA: {source.name} @{owner} hesabına ait ama @{account} seçildi.\n"
            f"Doğru hesapla çalıştır:  ./geri_cek.sh --account {owner}"
        )

    pending = load_pending(source)
    if not pending:
        sys.exit(f"HATA: {source} içinde bekleyen istek bulunamadı; dosya biçimi tanınmadı.")
    log(f"hesap: @{account}" + ("" if owner else " (dosyanın sahibi okunamadı, doğru hesap olduğundan emin ol)"))
    if not args.newest_first:
        pending.reverse()  # dosya en yeniden eskiye sıralı; eskiden başla

    state = load_state(GERI_CEK.state_path)
    acc_state = state.setdefault(account, {"withdrawn": {}, "skipped": {}})
    todo = [
        (u, d) for u, d in pending
        if u not in acc_state["withdrawn"] and acc_state["skipped"].get(u) not in FINAL_SKIPS
    ]

    log(f"kaynak: {rel(source)}")
    log(f"{len(pending)} bekleyen istek, {len(pending) - len(todo)} önceden halledilmiş, {len(todo)} kaldı.")
    if args.limit:
        todo = todo[: args.limit]
    if not todo:
        log("yapılacak bir şey yok.")
        return 0

    parallel, interval = plan_speed(args, len(todo))
    run = Run(args=args, account=account, total=len(todo), state=state, acc_state=acc_state,
              islem=GERI_CEK, parallel=parallel, interval=interval)
    return execute(run, todo, len(pending))

if __name__ == "__main__":
    sys.exit(main())
