"""geri_cek (withdraw_requests.py) için uçtan uca testler — sahte Instagram'a karşı.

    .venv/bin/python tests/run_tests.py          # hepsi (~4 dk)
    .venv/bin/python tests/run_tests.py 2 8      # sadece 2. ve 8. senaryo
"""
import json, os, pathlib, re, shutil, signal, subprocess, sys, time

HERE = pathlib.Path(__file__).resolve().parent
PY_BIN = str(HERE.parent / ".venv" / "bin" / "python")
ok = []


def check(name, cond, detail=""):
    ok.append(bool(cond))
    print(("  ✓ " if cond else "  ✗ ") + name + (f"  [{detail}]" if detail != "" else ""), flush=True)


def setup(name, users):
    tmp = HERE / "runs" / name
    shutil.rmtree(tmp, ignore_errors=True)
    (tmp / "downloads").mkdir(parents=True)
    rows = "".join(
        f'<div class="pam"><div class="_3-95"><div class="pam"><div class="_a6-p"><table>'
        f'<tr><td class="_a6_q">Username</td><td>{u}</td></tr></table></div></div></div>'
        f'<div class="_a6-o">Sep {i + 1:02d}, 2026 1:00 pm</div></div>'
        for i, u in enumerate(reversed(users)))  # dosya en yeni önce; script eskiden başlar
    (tmp / "downloads" / "pending_follow_requests.html").write_text(
        f'<html><body><header><h1>Pending</h1><aside>Generated by test.hesap on today</aside>'
        f'</header><main>{rows}</main></body></html>')
    return tmp


def run(tmp, argv, timeout=120, sigints=()):
    """sigints: [(saniye, ...)] — o anlarda bütün süreç grubuna SIGINT (terminaldeki Ctrl+C gibi)."""
    env = {**os.environ, "MOCK_CFG": json.dumps({"tmp": str(tmp), "argv": ["--account", "test.hesap", *argv]})}
    start = time.time()
    p = subprocess.Popen([PY_BIN, str(HERE / "mock_runner.py")], env=env, stdout=subprocess.PIPE,
                         stderr=subprocess.STDOUT, text=True, start_new_session=True)
    last_sig = None
    for at in sigints:
        time.sleep(max(0, start + at - time.time()))
        os.killpg(p.pid, signal.SIGINT)
        last_sig = time.time()
    hung = False
    try:
        out, _ = p.communicate(timeout=timeout)
    except subprocess.TimeoutExpired:
        hung = True
        os.kill(p.pid, signal.SIGUSR1)  # mock_runner'daki faulthandler yığını basar
        time.sleep(1.5)
        os.killpg(p.pid, signal.SIGKILL)
        out, _ = p.communicate()
        out += "\n<<TAKILDI — yukarıda yığın dökümü>>"
    dur = time.time() - (last_sig or start)
    return p.returncode, out, dur, hung


def state(tmp):
    f = tmp / "state.json"
    return json.loads(f.read_text())["test.hesap"] if f.exists() else {"withdrawn": {}, "skipped": {}}


def clicks(tmp):
    f = tmp / "clicks.log"
    return f.read_text().split() if f.exists() else []


def ratelog(tmp):
    f = tmp / "logs" / "rate_limit.log"
    return [json.loads(line) for line in f.read_text().splitlines()] if f.exists() else []


def leftover_chrome(tmp):
    return subprocess.run(["pgrep", "-f", f"user-data-dir={tmp}/profiles"], capture_output=True).returncode == 0


wanted = set(sys.argv[1:]) or {str(i) for i in range(1, 10)}

if "1" in wanted:
    print("\n[1] karışık liste, --hedef-dk 0.5 (30 profil ~30 sn)")
    users = [f"req_{i}" for i in range(20)] + ["fol_a", "fol_b", "fol_c", "gone_a", "gone_b",
                                               "flash_a", "flash_b", "flash_c", "nr_a", "req_x"]
    tmp = setup("s1", users)
    rc, out, dur, _ = run(tmp, ["--hedef-dk", "0.5"])
    st = state(tmp)
    check("çıkış kodu 0", rc == 0, rc)
    check("21 req + 3 flash = 24 geri çekildi", len(st["withdrawn"]) == 24, len(st["withdrawn"]))
    check("flash (önce Follow görünen) yanlışlıkla atlanmadı", all(f"flash_{c}" in st["withdrawn"] for c in "abc"))
    check("Following'e hiç tıklanmadı", not any("clicked_Following" in x for x in clicks(tmp)))
    check("fol → following, gone → not_found, nr → no_request",
          all(st["skipped"].get(k) == v for k, v in [("fol_a", "following"), ("gone_a", "not_found"), ("nr_a", "no_request")]))
    m = re.search(r"hedef ~0.5 dk: (\d+) sekme", out)
    check("sekme sayısı otomatik seçildi", m, m.group(0) if m else out[:300])
    check("süre hedefe yakın (25–60 sn)", 25 <= dur <= 60, f"{dur:.0f} sn")
    rl = ratelog(tmp)
    check("rate_limit.log: tamamlandi", rl and rl[-1]["sonuc"] == "tamamlandi")
    rc, out, _, _ = run(tmp, ["--hedef-dk", "0.5"])
    check("tekrar çalıştırma: yapılacak bir şey yok", "yapılacak bir şey yok" in out)

if "2" in wanted:
    print("\n[2] engel: 8. sırada 'Try Again Later', 3 sekme")
    users = [f"req_{i}" for i in range(7)] + ["block_x"] + [f"req_{i}" for i in range(7, 20)]
    tmp = setup("s2", users)
    rc, out, dur, _ = run(tmp, ["--parallel", "3", "--min-delay", "0", "--max-delay", "0"])
    st = state(tmp)
    check("çıkış kodu 1", rc == 1, rc)
    check("banner: INSTAGRAM ENGELLEDİ + sayfa mesajı", "INSTAGRAM ENGELLEDİ" in out and "Try Again Later" in out)
    check("banner'da işlem sayısı ve hız", re.search(r"bu çalıştırmada : \d+ profil işlendi", out) and "profil/dk" in out)
    c = clicks(tmp)
    after = c[c.index("blocked=block_x") + 1:] if "blocked=block_x" in c else []
    late = [x for x in after if x.startswith("clicked_requested")]
    check("engelden sonra yeni 'Requested' tıklaması yok (≤1)", len(late) <= 1, late)
    check("engel öncesi 7 profil geri çekildi", all(f"req_{i}" in st["withdrawn"] for i in range(7)))
    check("block_x sonra yeniden denenecek", st["skipped"].get("block_x") == "blocked")
    check("ekran görüntüsü alındı", list((tmp / "logs").glob("engel-*.png")))
    rl = ratelog(tmp)
    check("rate_limit.log: blocked", rl and rl[-1]["sonuc"] == "blocked")

if "3" in wanted:
    print("\n[3] sessiz engel: tıklama geri alınıyor")
    tmp = setup("s3", [f"silent_{i}" for i in range(6)])
    rc, out, _, _ = run(tmp, ["--min-delay", "0", "--max-delay", "0"])
    check("3 başarısızdan sonra durdu", "sessiz engel" in out and out.count("✗ başarısız") == 3, out.count("✗ başarısız"))
    check("çıkış kodu 1", rc == 1, rc)

if "4" in wanted:
    print("\n[4] doğrulama (checkpoint) sayfası")
    tmp = setup("s4", ["req_a", "req_b", "chk_a", "req_c", "req_d"])
    rc, out, _, _ = run(tmp, ["--min-delay", "0", "--max-delay", "0"])
    check("DOĞRULAMA banner'ı", "DOĞRULAMA İSTİYOR" in out)
    check("checkpoint'ten sonrası işlenmedi", set(state(tmp)["withdrawn"]) == {"req_a", "req_b"}, sorted(state(tmp)["withdrawn"]))

if "5" in wanted:
    print("\n[5] dry-run, 2 sekme")
    tmp = setup("s5", ["req_a", "req_b", "req_c", "fol_a", "gone_a"])
    rc, out, _, _ = run(tmp, ["--dry-run", "--parallel", "2", "--min-delay", "0", "--max-delay", "0"])
    check("hiçbir tıklama yok", clicks(tmp) == [], clicks(tmp))
    check("state'e geri çekme yazılmadı", not state(tmp)["withdrawn"])
    check("özet: 3 bekliyor, 1 kabul", "hâlâ bekliyor (geri çekilebilir)   3" in out and "kabul etmiş, dokunulmadı           1" in out)

if "6" in wanted:
    print("\n[6] --watch (tek sekme, işaretlemeli)")
    tmp = setup("s6", ["req_a", "fol_a", "req_b"])
    rc, out, _, _ = run(tmp, ["--watch", "--parallel", "4", "--min-delay", "0", "--max-delay", "0"])
    check("watch'ta sekme 1'e indi", "sekme sayısı 1'e indirildi" in out)
    check("2 geri çekildi, Following'e dokunulmadı",
          len(state(tmp)["withdrawn"]) == 2 and not any("Following" in x for x in clicks(tmp)))

if "7" in wanted:
    print("\n[7] tek Ctrl+C: sekmeler eldeki profili bitirip durur")
    tmp = setup("s7", [f"req_{i}" for i in range(60)])
    rc, out, dur, hung = run(tmp, ["--parallel", "2", "--min-delay", "1", "--max-delay", "1"], timeout=30, sigints=[12])
    st = state(tmp)
    check("takılmadı, 15 sn içinde çıktı", not hung and dur < 15, f"{dur:.1f} sn")
    check("durduruluyor mesajı + KULLANICI DURDURDU + özet", "durduruluyor" in out and "KULLANICI DURDURDU" in out and "ÖZET" in out)
    check("ilerleme kaydedildi", 3 <= len(st["withdrawn"]) < 60, len(st["withdrawn"]))
    check("Traceback yok", "Traceback" not in out, out[out.find("Traceback"):][:300] if "Traceback" in out else "")
    check("geride Chrome kalmadı", not leftover_chrome(tmp))

if "8" in wanted:
    print("\n[8] iki kez Ctrl+C (0,5 sn arayla): hemen çıkmalı, takılmamalı")
    tmp = setup("s8", [f"req_{i}" for i in range(60)])
    rc, out, dur, hung = run(tmp, ["--hedef-dk", "3"], timeout=20, sigints=[10, 10.5])
    st = state(tmp)
    check("takılmadı, 10 sn içinde çıktı", not hung and dur < 10, f"{dur:.1f} sn" + (" TAKILDI" if hung else ""))
    check("kayıt bozulmadı", isinstance(st.get("withdrawn"), dict) and len(st["withdrawn"]) >= 1, len(st.get("withdrawn", {})))
    check("geride Chrome kalmadı", not leftover_chrome(tmp))
    if hung or "Traceback" in out:
        print("   ---- çıktının sonu ----")
        print("\n".join("   " + line for line in out[-3500:].splitlines()))

if "9" in wanted:
    print("\n[9] --gonderilenler: istek_at'in gönderdiklerini geri çeker, export gerekmez")
    tmp = setup("s9", [])
    (tmp / "follow_state.json").write_text(json.dumps({"test.hesap": {"sent": {
        "req_1": "2026-09-30T22:00:00", "req_2": "2026-09-30T22:01:00",
        "nr_a": "2026-09-30T22:02:00", "req_3": "2026-09-30T22:03:00"}, "skipped": {}}}))
    # req_1: eski "istek yok" kaydı, req_2: bu gönderimden ÖNCE geri çekilmiş -> ikisi de çekilmeli
    # req_3: bu gönderimden SONRA zaten geri çekilmiş -> dokunulmamalı
    (tmp / "state.json").write_text(json.dumps({"test.hesap": {
        "withdrawn": {"req_2": "2026-09-01T10:00:00", "req_3": "2026-10-01T10:00:00"},
        "skipped": {"req_1": "no_request"}}}))
    rc, out, _, _ = run(tmp, ["--gonderilenler", "--min-delay", "0", "--max-delay", "0"])
    st = state(tmp)
    c = clicks(tmp)
    check("çıkış kodu 0", rc == 0, out[-300:] if rc else rc)
    check("kaynak follow_state.json: 4 istek, 1 önceden halledilmiş, 3 kaldı",
          "follow_state.json" in out and "4 bekleyen istek, 1 önceden halledilmiş, 3 kaldı" in out, out[:600])
    check("eski kayıtlara rağmen req_1 ve req_2 geri çekildi",
          st["withdrawn"].get("req_1", "") > "2026-10" and st["withdrawn"].get("req_2", "") > "2026-10", st["withdrawn"])
    check("gönderimden sonra zaten çekilmiş req_3'e dokunulmadı",
          "clicked_requested=req_3" not in c and st["withdrawn"]["req_3"] == "2026-10-01T10:00:00")
    check("isteği düşmüş nr_a: bekleyen istek yok", st["skipped"].get("nr_a") == "no_request", st["skipped"])
    rc, out, _, _ = run(tmp, ["--gonderilenler", "--file", "x.html"])
    check("--gonderilenler ile --file birlikte verilemez", rc != 0 and "not allowed with argument" in out, out[-200:])

print(f"\nSONUÇ: {sum(ok)}/{len(ok)}")
sys.exit(0 if all(ok) else 1)
